# Generated by Django 4.0.3 on 2023-06-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='binvo',
            name='bin_number',
        ),
        migrations.RemoveField(
            model_name='binvo',
            name='bin_size',
        ),
        migrations.AddField(
            model_name='binvo',
            name='import_href',
            field=models.CharField(default='/api/bins/1/', max_length=100),
            preserve_default=False,
        ),
    ]
